#!/usr/bin/env python3
   
a = int
a = input('What is your number? ')
   
if int(a)%3 == 0 and int(a)%5 == 0:
   print ('FizzBuzz')
elif int(a)%3 == 0:
   print ('Fizz')
elif int(a)%5 == 0:
   print ('Buzz')
else:
   print(a)
